dependencies:
    - smartcontractkit/chainlink-brownie-contracts@0.4.0
    - OpenZeppelin/openzeppelin-contracts@4.3.2
compiler:
    solc:
        remappings:
            - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0"
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2"
# automatically fetch contract sources from Etherscan
autofetch_sources: True
# Uncomment to use the .env file
# dotenv: .env
# set a custom mnemonic for the development network
networks:
    default: development
    development:
        fee: 100000000000000000
        fund_amount: 5000000000000000000
        gas_lane: "0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc"
        jobId: 29fa9aa13bf1468788b7cc4a500a45b8
        keyhash: "0x6c3699283bda56ad74f6b855546325b68d482e983852a7a82979cc4807b641f4"
        update_interval: 60
        verify: false
    fuji:
        fee: 100000000000000000
        jobId: 5ca4fa9b2d64462290abfbda84e38cf4
        link_token: "0x0b9d5D9136855f6FEc3c0993feE6E9CE8a297846"
        oracle: "0xcc80934eaf22b2c8dbf7a69e8e0d356a7cac5754"
    ganache:
        fee: 100000000000000000
        jobId: 29fa9aa13bf1468788b7cc4a500a45b8
        keyhash: "0x6c3699283bda56ad74f6b855546325b68d482e983852a7a82979cc4807b641f4"
        update_interval: 60
        verify: false
    kovan:
        eth_usd_price_feed: "0x9326BFA02ADD2366b30bacB125260Af641031331"
        fee: 100000000000000000
        jobId: d5270d1c311941d0b08bead21fea7747
        link_token: "0xa36085F69e2889c224210F603D836748e7dC0088"
        oracle: "0xc57b33452b4f7bb189bb5afae9cc4aba1f7a4fd8"
        update_interval: 60
        verify: true
    mumbai:
        eth_usd_price_feed: "0x0715A7794a1dc8e42615F059dD6e406A6594651A"
        fee: 1000000000000000000
        keyhash: "0x6e75b569a01ef56d18cab6a8e71e6600d6ce853834d4a5748b720d06f878b3a4"
        link_token: "0x326C977E6efc84E512bB9C30f76E30c160eD06FB"
        vrf_coordinator: "0x8C7382F9D8f56b33781fE506E897a4F1e2d17255"
    rinkeby:
        eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
        fee: 100000000000000000
        fund_amount: 5000000000000000000
        gas_lane: "0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc"
        jobId: 6b88e0402e5d415eb946e528b8e0c7ba
        keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
        link_token: "0x01be23585060835e02b77ef475b0cc51aa1e0709"
        oracle: "0xc57b33452b4f7bb189bb5afae9cc4aba1f7a4fd8"
        # Add your sub_id
        # subscription_id: 1003
        verify: false
        vrf_coordinator: "0x6168499c0cFfCaCD319c818142124B7A15E857ab"
reports:
    exclude_contracts:
        - SafeMath
wallets:
    from_key: ${PRIVATE_KEY}
