# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - alphachainio/chainlink-contracts@1.1.0
compiler:
  solc:
    remappings:
      - '@chainlink=alphachainio/chainlink-contracts@1.1.0'
# automatically fetch contract sources from Etherscan
autofetch_sources: True
# set a custom mnemonic for the development network
networks:
  default: mainnet-fork
  kovan:
    vrf_coordinator: '0xdD3782915140c8f3b190B5D67eAc6dc5760C46E9'
    link_token: '0xa36085F69e2889c224210F603D836748e7dC0088'
    keyhash: '0x6c3699283bda56ad74f6b855546325b68d482e983852a7a82979cc4807b641f4'
    fee: 100000000000000000
    oracle: '0x2f90A6D021db21e1B2A077c5a37B3C7E75D15b7e'
    jobId: '29fa9aa13bf1468788b7cc4a500a45b8'
  rinkeby:
    vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
    link_token: '0x01be23585060835e02b77ef475b0cc51aa1e0709'
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 100000000000000000
    oracle: '0x7AFe1118Ea78C1eae84ca8feE5C65Bc76CcF879e'
    jobId: '6d1bfe27e7034b1d87b5270556b17277'
wallets:
  from_key: PRIVATE_KEY
  # could also do from_mnemonic, and you'd have to change the accounts.add to accounts.from_mnemonic
